services:
  grafana-lgtm:
    image: grafana/otel-lgtm:0.8.1
    container_name: lgtm
    restart: always
    ports:
      - "3000:3000"
      - "4317-4318:4317-4318"
  db:
    container_name: db
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
